# Generated by Django 3.1.5 on 2021-02-02 14:23

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210202_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.TimeField(default=orders.models.Order.return_delivery),
        ),
    ]
