# Generated by Django 3.1.5 on 2021-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210202_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=250)),
                ('building', models.CharField(choices=[('Quantile', 'Quantile'), ('Herb Str', 'Herb Str'), ('Minller Str', 'Minller Str')], max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
