# Generated by Django 3.1.5 on 2021-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='ordered_product',
            field=models.CharField(default=5, max_length=250),
            preserve_default=False,
        ),
    ]
