# Generated by Django 3.1.5 on 2021-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_serviceorder_ordered_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=250)),
                ('building', models.CharField(choices=[('Quintal', 'Quintal'), ('2 Herb Street', '2 Herb Street'), ('Miller', 'Miller')], max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=5)),
                ('ordered_product', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
