# Generated by Django 3.1.5 on 2021-01-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
