# Generated by Django 3.1.5 on 2021-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0005_product_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('PI', 'per item'), ('P', 'per packet'), ('PS', 'per plastic')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='product',
            name='slide_image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%M/%D'),
        ),
    ]
