# Generated by Django 3.1.5 on 2021-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0008_auto_20210128_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_slide_image', models.ImageField(upload_to='specials')),
                ('second_slide_image', models.ImageField(upload_to='specials')),
                ('third_slide_image', models.ImageField(upload_to='specials')),
            ],
        ),
    ]
