# Generated by Django 3.1.5 on 2021-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0009_month_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_special',
            name='note_on_ordering',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='month_special',
            name='procedure_for_ordering',
            field=models.TextField(blank=True),
        ),
    ]
