# Generated by Django 3.1.3 on 2021-03-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0010_auto_20210218_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_special',
            name='it_is_advertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='month_special',
            name='it_is_youtube_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='month_special',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
