# Generated by Django 3.1.3 on 2021-03-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetItApp', '0011_auto_20210304_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_special',
            name='first_slide_image',
            field=models.ImageField(blank=True, upload_to='specials'),
        ),
        migrations.AlterField(
            model_name='month_special',
            name='second_slide_image',
            field=models.ImageField(blank=True, upload_to='specials'),
        ),
        migrations.AlterField(
            model_name='month_special',
            name='third_slide_image',
            field=models.ImageField(blank=True, upload_to='specials'),
        ),
    ]
